apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: accountdepl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        command: [
      	  "./nanosapp.account",
      	  "--server_address=0.0.0.0:8080",
      	  "--broker_address=0.0.0.0:10001",
      	  "--selector=static",
      	]
        image: livelance/nanoaccount:v0.0.1
        env:
          - name: DB_USER
            value: "postgres"
          - name: DB_PASS
            value: ""
          - name: DB_NAME
            value: "nanoaccount"
        ports:
        - containerPort: 8080
          name: srvc-port
        - containerPort: 8081
          name: account-port