---
kind: Service
apiVersion: v1
metadata:
  name: account
  namespace: default
  labels:
      app: account
spec:
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8081
    nodePort: 30002
  selector:
      app: account

---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: account