// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/adCampaign/proto/adCampaign.proto

package adcampaign

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	AdCampaigns          []*AdCampaign `protobuf:"bytes,1,rep,name=adCampaigns,proto3" json:"adCampaigns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAdCampaigns() []*AdCampaign {
	if m != nil {
		return m.AdCampaigns
	}
	return nil
}

type AdCampaign struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Goal                 string     `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	TotalBudget          int64      `protobuf:"varint,4,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	Status               string     `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Platforms            *Platforms `protobuf:"bytes,6,opt,name=platforms,proto3" json:"platforms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdCampaign) Reset()         { *m = AdCampaign{} }
func (m *AdCampaign) String() string { return proto.CompactTextString(m) }
func (*AdCampaign) ProtoMessage()    {}
func (*AdCampaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{2}
}
func (m *AdCampaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdCampaign.Unmarshal(m, b)
}
func (m *AdCampaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdCampaign.Marshal(b, m, deterministic)
}
func (dst *AdCampaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdCampaign.Merge(dst, src)
}
func (m *AdCampaign) XXX_Size() int {
	return xxx_messageInfo_AdCampaign.Size(m)
}
func (m *AdCampaign) XXX_DiscardUnknown() {
	xxx_messageInfo_AdCampaign.DiscardUnknown(m)
}

var xxx_messageInfo_AdCampaign proto.InternalMessageInfo

func (m *AdCampaign) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdCampaign) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdCampaign) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

func (m *AdCampaign) GetTotalBudget() int64 {
	if m != nil {
		return m.TotalBudget
	}
	return 0
}

func (m *AdCampaign) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AdCampaign) GetPlatforms() *Platforms {
	if m != nil {
		return m.Platforms
	}
	return nil
}

type Platforms struct {
	Facebook             *Platform `protobuf:"bytes,1,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Instagram            *Platform `protobuf:"bytes,2,opt,name=instagram,proto3" json:"instagram,omitempty"`
	Google               *Platform `protobuf:"bytes,3,opt,name=google,proto3" json:"google,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Platforms) Reset()         { *m = Platforms{} }
func (m *Platforms) String() string { return proto.CompactTextString(m) }
func (*Platforms) ProtoMessage()    {}
func (*Platforms) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{3}
}
func (m *Platforms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Platforms.Unmarshal(m, b)
}
func (m *Platforms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Platforms.Marshal(b, m, deterministic)
}
func (dst *Platforms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Platforms.Merge(dst, src)
}
func (m *Platforms) XXX_Size() int {
	return xxx_messageInfo_Platforms.Size(m)
}
func (m *Platforms) XXX_DiscardUnknown() {
	xxx_messageInfo_Platforms.DiscardUnknown(m)
}

var xxx_messageInfo_Platforms proto.InternalMessageInfo

func (m *Platforms) GetFacebook() *Platform {
	if m != nil {
		return m.Facebook
	}
	return nil
}

func (m *Platforms) GetInstagram() *Platform {
	if m != nil {
		return m.Instagram
	}
	return nil
}

func (m *Platforms) GetGoogle() *Platform {
	if m != nil {
		return m.Google
	}
	return nil
}

type Platform struct {
	Status               string          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalBudget          int64           `protobuf:"varint,2,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	RemainingBudget      int64           `protobuf:"varint,3,opt,name=remaining_budget,json=remainingBudget,proto3" json:"remaining_budget,omitempty"`
	StartDate            int64           `protobuf:"varint,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              int64           `protobuf:"varint,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TargetAudiance       *TargetAudiance `protobuf:"bytes,6,opt,name=target_audiance,json=targetAudiance,proto3" json:"target_audiance,omitempty"`
	Creatives            *Creatives      `protobuf:"bytes,7,opt,name=creatives,proto3" json:"creatives,omitempty"`
	Insights             *Insights       `protobuf:"bytes,8,opt,name=insights,proto3" json:"insights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Platform) Reset()         { *m = Platform{} }
func (m *Platform) String() string { return proto.CompactTextString(m) }
func (*Platform) ProtoMessage()    {}
func (*Platform) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{4}
}
func (m *Platform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Platform.Unmarshal(m, b)
}
func (m *Platform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Platform.Marshal(b, m, deterministic)
}
func (dst *Platform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Platform.Merge(dst, src)
}
func (m *Platform) XXX_Size() int {
	return xxx_messageInfo_Platform.Size(m)
}
func (m *Platform) XXX_DiscardUnknown() {
	xxx_messageInfo_Platform.DiscardUnknown(m)
}

var xxx_messageInfo_Platform proto.InternalMessageInfo

func (m *Platform) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Platform) GetTotalBudget() int64 {
	if m != nil {
		return m.TotalBudget
	}
	return 0
}

func (m *Platform) GetRemainingBudget() int64 {
	if m != nil {
		return m.RemainingBudget
	}
	return 0
}

func (m *Platform) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *Platform) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *Platform) GetTargetAudiance() *TargetAudiance {
	if m != nil {
		return m.TargetAudiance
	}
	return nil
}

func (m *Platform) GetCreatives() *Creatives {
	if m != nil {
		return m.Creatives
	}
	return nil
}

func (m *Platform) GetInsights() *Insights {
	if m != nil {
		return m.Insights
	}
	return nil
}

type TargetAudiance struct {
	Languages            []string `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	Genders              []string `protobuf:"bytes,2,rep,name=genders,proto3" json:"genders,omitempty"`
	AgeRange             []int64  `protobuf:"varint,3,rep,packed,name=age_range,json=ageRange,proto3" json:"age_range,omitempty"`
	Locations            []string `protobuf:"bytes,4,rep,name=locations,proto3" json:"locations,omitempty"`
	KeyWords             []string `protobuf:"bytes,5,rep,name=keyWords,proto3" json:"keyWords,omitempty"`
	Interests            []string `protobuf:"bytes,6,rep,name=interests,proto3" json:"interests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetAudiance) Reset()         { *m = TargetAudiance{} }
func (m *TargetAudiance) String() string { return proto.CompactTextString(m) }
func (*TargetAudiance) ProtoMessage()    {}
func (*TargetAudiance) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{5}
}
func (m *TargetAudiance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetAudiance.Unmarshal(m, b)
}
func (m *TargetAudiance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetAudiance.Marshal(b, m, deterministic)
}
func (dst *TargetAudiance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetAudiance.Merge(dst, src)
}
func (m *TargetAudiance) XXX_Size() int {
	return xxx_messageInfo_TargetAudiance.Size(m)
}
func (m *TargetAudiance) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetAudiance.DiscardUnknown(m)
}

var xxx_messageInfo_TargetAudiance proto.InternalMessageInfo

func (m *TargetAudiance) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *TargetAudiance) GetGenders() []string {
	if m != nil {
		return m.Genders
	}
	return nil
}

func (m *TargetAudiance) GetAgeRange() []int64 {
	if m != nil {
		return m.AgeRange
	}
	return nil
}

func (m *TargetAudiance) GetLocations() []string {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *TargetAudiance) GetKeyWords() []string {
	if m != nil {
		return m.KeyWords
	}
	return nil
}

func (m *TargetAudiance) GetInterests() []string {
	if m != nil {
		return m.Interests
	}
	return nil
}

type Creatives struct {
	Header               string   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Header1              string   `protobuf:"bytes,2,opt,name=header1,proto3" json:"header1,omitempty"`
	Header2              string   `protobuf:"bytes,3,opt,name=header2,proto3" json:"header2,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	URL                  string   `protobuf:"bytes,5,opt,name=URL,proto3" json:"URL,omitempty"`
	Image                string   `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Creatives) Reset()         { *m = Creatives{} }
func (m *Creatives) String() string { return proto.CompactTextString(m) }
func (*Creatives) ProtoMessage()    {}
func (*Creatives) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{6}
}
func (m *Creatives) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Creatives.Unmarshal(m, b)
}
func (m *Creatives) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Creatives.Marshal(b, m, deterministic)
}
func (dst *Creatives) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Creatives.Merge(dst, src)
}
func (m *Creatives) XXX_Size() int {
	return xxx_messageInfo_Creatives.Size(m)
}
func (m *Creatives) XXX_DiscardUnknown() {
	xxx_messageInfo_Creatives.DiscardUnknown(m)
}

var xxx_messageInfo_Creatives proto.InternalMessageInfo

func (m *Creatives) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Creatives) GetHeader1() string {
	if m != nil {
		return m.Header1
	}
	return ""
}

func (m *Creatives) GetHeader2() string {
	if m != nil {
		return m.Header2
	}
	return ""
}

func (m *Creatives) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Creatives) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Creatives) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Insights struct {
	Impressions          int64    `protobuf:"varint,1,opt,name=impressions,proto3" json:"impressions,omitempty"`
	Clicks               int64    `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	WebsiteVisits        int64    `protobuf:"varint,3,opt,name=website_visits,json=websiteVisits,proto3" json:"website_visits,omitempty"`
	CostPerClick         float64  `protobuf:"fixed64,4,opt,name=cost_per_click,json=costPerClick,proto3" json:"cost_per_click,omitempty"`
	ClickThroughRate     float64  `protobuf:"fixed64,5,opt,name=click_through_rate,json=clickThroughRate,proto3" json:"click_through_rate,omitempty"`
	AdvancedKpi_1        float64  `protobuf:"fixed64,6,opt,name=advanced_kpi_1,json=advancedKpi1,proto3" json:"advanced_kpi_1,omitempty"`
	AdvancedKpi_2        float64  `protobuf:"fixed64,7,opt,name=advanced_kpi_2,json=advancedKpi2,proto3" json:"advanced_kpi_2,omitempty"`
	NanosScore           float64  `protobuf:"fixed64,8,opt,name=nanos_score,json=nanosScore,proto3" json:"nanos_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insights) Reset()         { *m = Insights{} }
func (m *Insights) String() string { return proto.CompactTextString(m) }
func (*Insights) ProtoMessage()    {}
func (*Insights) Descriptor() ([]byte, []int) {
	return fileDescriptor_adCampaign_7477ba2216f74e18, []int{7}
}
func (m *Insights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insights.Unmarshal(m, b)
}
func (m *Insights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insights.Marshal(b, m, deterministic)
}
func (dst *Insights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insights.Merge(dst, src)
}
func (m *Insights) XXX_Size() int {
	return xxx_messageInfo_Insights.Size(m)
}
func (m *Insights) XXX_DiscardUnknown() {
	xxx_messageInfo_Insights.DiscardUnknown(m)
}

var xxx_messageInfo_Insights proto.InternalMessageInfo

func (m *Insights) GetImpressions() int64 {
	if m != nil {
		return m.Impressions
	}
	return 0
}

func (m *Insights) GetClicks() int64 {
	if m != nil {
		return m.Clicks
	}
	return 0
}

func (m *Insights) GetWebsiteVisits() int64 {
	if m != nil {
		return m.WebsiteVisits
	}
	return 0
}

func (m *Insights) GetCostPerClick() float64 {
	if m != nil {
		return m.CostPerClick
	}
	return 0
}

func (m *Insights) GetClickThroughRate() float64 {
	if m != nil {
		return m.ClickThroughRate
	}
	return 0
}

func (m *Insights) GetAdvancedKpi_1() float64 {
	if m != nil {
		return m.AdvancedKpi_1
	}
	return 0
}

func (m *Insights) GetAdvancedKpi_2() float64 {
	if m != nil {
		return m.AdvancedKpi_2
	}
	return 0
}

func (m *Insights) GetNanosScore() float64 {
	if m != nil {
		return m.NanosScore
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "adcampaign.Request")
	proto.RegisterType((*Response)(nil), "adcampaign.Response")
	proto.RegisterType((*AdCampaign)(nil), "adcampaign.AdCampaign")
	proto.RegisterType((*Platforms)(nil), "adcampaign.Platforms")
	proto.RegisterType((*Platform)(nil), "adcampaign.Platform")
	proto.RegisterType((*TargetAudiance)(nil), "adcampaign.TargetAudiance")
	proto.RegisterType((*Creatives)(nil), "adcampaign.Creatives")
	proto.RegisterType((*Insights)(nil), "adcampaign.Insights")
}

func init() {
	proto.RegisterFile("services/adCampaign/proto/adCampaign.proto", fileDescriptor_adCampaign_7477ba2216f74e18)
}

var fileDescriptor_adCampaign_7477ba2216f74e18 = []byte{
	// 769 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x4d, 0x8f, 0x23, 0x35,
	0x10, 0xa5, 0x93, 0x99, 0x4c, 0x77, 0x65, 0xc8, 0x0e, 0x66, 0x58, 0x35, 0x03, 0x68, 0x87, 0xd6,
	0x22, 0x0d, 0x68, 0x35, 0xcb, 0xf4, 0x0a, 0x89, 0xeb, 0x90, 0x95, 0x10, 0x1f, 0x87, 0x95, 0x77,
	0x81, 0x63, 0xcb, 0xe9, 0xae, 0x75, 0xac, 0x74, 0xec, 0xc6, 0x76, 0x82, 0xf8, 0x35, 0x88, 0x3b,
	0x47, 0xae, 0xfc, 0x0d, 0x7e, 0x0f, 0xb2, 0xdb, 0xfd, 0x11, 0xb2, 0x7b, 0x73, 0xbd, 0xf7, 0x5c,
	0x71, 0x55, 0xbd, 0xae, 0xc0, 0x17, 0x06, 0xf5, 0x5e, 0x94, 0x68, 0x9e, 0xb2, 0x6a, 0xc9, 0xb6,
	0x0d, 0x13, 0x5c, 0x3e, 0x6d, 0xb4, 0xb2, 0x6a, 0x04, 0xdc, 0x7a, 0x80, 0x00, 0xab, 0xca, 0x80,
	0x64, 0x8f, 0xe0, 0x8c, 0xe2, 0xaf, 0x3b, 0x34, 0x96, 0x5c, 0xc2, 0xa9, 0x55, 0x1b, 0x94, 0x69,
	0x74, 0x1d, 0xdd, 0x24, 0xb4, 0x0d, 0xb2, 0xe7, 0x10, 0x53, 0x34, 0x8d, 0x92, 0x06, 0xc9, 0xd7,
	0x30, 0x1f, 0x92, 0x99, 0x34, 0xba, 0x9e, 0xde, 0xcc, 0xf3, 0x87, 0xb7, 0x43, 0xba, 0xdb, 0xfb,
	0x9e, 0xa6, 0x63, 0x69, 0xf6, 0x77, 0x04, 0x30, 0x70, 0x64, 0x01, 0x13, 0x51, 0xf9, 0xdf, 0x99,
	0xd2, 0x89, 0xa8, 0x08, 0x81, 0x13, 0xc9, 0xb6, 0x98, 0x4e, 0xfc, 0x2f, 0xfb, 0xb3, 0xc3, 0xb8,
	0x62, 0x75, 0x3a, 0x6d, 0x31, 0x77, 0x26, 0x9f, 0xc2, 0xb9, 0x55, 0x96, 0xd5, 0xc5, 0x6a, 0x57,
	0x71, 0xb4, 0xe9, 0x89, 0xcf, 0x30, 0xf7, 0xd8, 0x37, 0x1e, 0x22, 0x0f, 0x61, 0x66, 0x2c, 0xb3,
	0x3b, 0x93, 0x9e, 0xfa, 0x8b, 0x21, 0x22, 0xcf, 0x20, 0x69, 0x6a, 0x66, 0x5f, 0x2b, 0xbd, 0x35,
	0xe9, 0xec, 0x3a, 0xba, 0x99, 0xe7, 0x1f, 0x8c, 0x5f, 0xfe, 0xa2, 0x23, 0xe9, 0xa0, 0xcb, 0xfe,
	0x88, 0x20, 0xe9, 0x09, 0xf2, 0x25, 0xc4, 0xaf, 0x59, 0x89, 0x2b, 0xa5, 0x36, 0xfe, 0xed, 0xf3,
	0xfc, 0xf2, 0x4d, 0x19, 0x68, 0xaf, 0x22, 0x39, 0x24, 0x42, 0x1a, 0xcb, 0xb8, 0x66, 0x5b, 0x5f,
	0xdc, 0xdb, 0xae, 0x0c, 0x32, 0xf2, 0x04, 0x66, 0x5c, 0x29, 0x5e, 0xa3, 0xaf, 0xfc, 0x6d, 0x17,
	0x82, 0x26, 0xfb, 0x77, 0x02, 0x71, 0x07, 0x8e, 0x6a, 0x8f, 0x0e, 0x6a, 0xff, 0x7f, 0xdb, 0x26,
	0xc7, 0x6d, 0xfb, 0x1c, 0x2e, 0x34, 0x6e, 0x99, 0x90, 0x42, 0xf2, 0x4e, 0x36, 0xf5, 0xb2, 0x07,
	0x3d, 0x1e, 0xa4, 0x9f, 0x00, 0x18, 0xcb, 0xb4, 0x2d, 0x2a, 0x66, 0x31, 0x8c, 0x20, 0xf1, 0xc8,
	0x73, 0x66, 0x91, 0x7c, 0x08, 0x31, 0xca, 0xaa, 0x25, 0x4f, 0x3d, 0x79, 0x86, 0xb2, 0xf2, 0xd4,
	0x12, 0x1e, 0x58, 0xa6, 0x39, 0xda, 0x82, 0xed, 0x2a, 0xc1, 0x64, 0x89, 0x61, 0x12, 0x57, 0xe3,
	0x1a, 0x5f, 0x79, 0xc9, 0x7d, 0x50, 0xd0, 0x85, 0x3d, 0x88, 0xdd, 0x20, 0x4b, 0x8d, 0xcc, 0x8a,
	0x3d, 0x9a, 0xf4, 0xec, 0x78, 0x90, 0xcb, 0x8e, 0xa4, 0x83, 0xce, 0x8d, 0x4e, 0x48, 0x23, 0xf8,
	0xda, 0x9a, 0x34, 0x3e, 0x6e, 0xeb, 0x77, 0x81, 0xa3, 0xbd, 0x2a, 0xfb, 0x27, 0x82, 0xc5, 0xe1,
	0x4b, 0xc8, 0xc7, 0x90, 0xd4, 0x4c, 0xf2, 0x1d, 0xe3, 0xd8, 0x9a, 0x3f, 0xa1, 0x03, 0x40, 0x52,
	0x38, 0xe3, 0x28, 0x2b, 0xd4, 0x26, 0x9d, 0x78, 0xae, 0x0b, 0xc9, 0x47, 0x90, 0x30, 0x8e, 0x85,
	0x66, 0x92, 0xbb, 0xa1, 0x4e, 0x6f, 0xa6, 0x34, 0x66, 0x1c, 0xa9, 0x8b, 0x7d, 0x52, 0x55, 0x32,
	0x2b, 0x94, 0x34, 0xe9, 0x49, 0x48, 0xda, 0x01, 0xe4, 0x0a, 0xe2, 0x0d, 0xfe, 0xfe, 0x8b, 0xd2,
	0x95, 0xf3, 0xb3, 0x23, 0xfb, 0xd8, 0xdd, 0x14, 0xd2, 0xa2, 0x46, 0x63, 0x9d, 0xa3, 0xfd, 0xcd,
	0x1e, 0xc8, 0xfe, 0x8c, 0x20, 0xe9, 0x5b, 0xe1, 0x9c, 0xb1, 0x46, 0x56, 0xa1, 0xee, 0x9c, 0xd1,
	0x46, 0xee, 0xd1, 0xed, 0xe9, 0x2e, 0x7c, 0x7b, 0x5d, 0x38, 0x30, 0x79, 0xf8, 0x02, 0xbb, 0x90,
	0x5c, 0xc3, 0xbc, 0x42, 0x53, 0x6a, 0xd1, 0xb8, 0x37, 0x7a, 0x03, 0x24, 0x74, 0x0c, 0x91, 0x0b,
	0x98, 0xfe, 0x44, 0x7f, 0x0c, 0x1f, 0xa0, 0x3b, 0xba, 0xdd, 0x22, 0xb6, 0x8c, 0xb7, 0xf3, 0x4e,
	0x68, 0x1b, 0x64, 0x7f, 0x4d, 0x20, 0xee, 0x5a, 0xef, 0xd2, 0x8a, 0x6d, 0xa3, 0xd1, 0x18, 0xdf,
	0x8a, 0x76, 0x39, 0x8c, 0x21, 0x57, 0x44, 0x59, 0x8b, 0x72, 0x63, 0x82, 0x81, 0x43, 0x44, 0x3e,
	0x83, 0xc5, 0x6f, 0xb8, 0x32, 0xc2, 0x62, 0xb1, 0x17, 0x46, 0x58, 0x13, 0x9c, 0xfb, 0x6e, 0x40,
	0x7f, 0xf6, 0x20, 0x79, 0x0c, 0x8b, 0x52, 0x19, 0x5b, 0x34, 0xa8, 0x0b, 0x7f, 0xd3, 0x3f, 0x3d,
	0xa2, 0xe7, 0x0e, 0x7d, 0x81, 0x7a, 0xe9, 0x30, 0xf2, 0x04, 0x88, 0x27, 0x0b, 0xbb, 0xd6, 0x6a,
	0xc7, 0xd7, 0x85, 0xee, 0x8c, 0x1c, 0xd1, 0x0b, 0xcf, 0xbc, 0x6a, 0x09, 0xea, 0x1c, 0xfd, 0x18,
	0x16, 0xac, 0xda, 0x3b, 0x77, 0x54, 0xc5, 0xa6, 0x11, 0xc5, 0x9d, 0x2f, 0x30, 0xa2, 0xe7, 0x1d,
	0xfa, 0x43, 0x23, 0xee, 0x8e, 0x54, 0xb9, 0xf7, 0xed, 0xa1, 0x2a, 0x27, 0x8f, 0x60, 0x2e, 0x99,
	0x54, 0xa6, 0x30, 0xa5, 0xd2, 0xe8, 0x6d, 0x1a, 0x51, 0xf0, 0xd0, 0x4b, 0x87, 0xe4, 0xdf, 0xc3,
	0x7b, 0xc3, 0x0e, 0x7d, 0xd9, 0xee, 0x7b, 0xf2, 0x15, 0xcc, 0xbe, 0x45, 0x7b, 0x5f, 0xd7, 0xe4,
	0xfd, 0xb1, 0xa3, 0xc3, 0x52, 0xbf, 0xba, 0x3c, 0x04, 0xdb, 0x45, 0x9e, 0xbd, 0xb3, 0x9a, 0xf9,
	0xbf, 0x82, 0x67, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x4c, 0x0c, 0x96, 0x38, 0x06, 0x00,
	0x00,
}
