apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: adcampaigndepl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: adcampaign
    spec:
      containers:
      - name: adcampaign
        command: [
      	  "./nanosapp.adCampaign",
      	  "--server_address=0.0.0.0:8080",
      	  "--broker_address=0.0.0.0:10001",
      	  "--selector=static",
      	]
        image: nanosapp/adcampaign:v0.0.1
        env:
          - name: DB_SERVER
            value: "mongo:27017"
          - name: DB_NAME
            value: "ad_campaigns"
        ports:
        - containerPort: 8080
          name: srvc-port
        - containerPort: 8081
          name: adcampaign-port