// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/account/proto/account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountGetRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountGetRequest) Reset()         { *m = AccountGetRequest{} }
func (m *AccountGetRequest) String() string { return proto.CompactTextString(m) }
func (*AccountGetRequest) ProtoMessage()    {}
func (*AccountGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_58c98afeafbb3e14, []int{0}
}
func (m *AccountGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountGetRequest.Unmarshal(m, b)
}
func (m *AccountGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountGetRequest.Marshal(b, m, deterministic)
}
func (dst *AccountGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountGetRequest.Merge(dst, src)
}
func (m *AccountGetRequest) XXX_Size() int {
	return xxx_messageInfo_AccountGetRequest.Size(m)
}
func (m *AccountGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountGetRequest proto.InternalMessageInfo

func (m *AccountGetRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AccountResponse struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_58c98afeafbb3e14, []int{1}
}
func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (dst *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(dst, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type AccountAddRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAddRequest) Reset()         { *m = AccountAddRequest{} }
func (m *AccountAddRequest) String() string { return proto.CompactTextString(m) }
func (*AccountAddRequest) ProtoMessage()    {}
func (*AccountAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_58c98afeafbb3e14, []int{2}
}
func (m *AccountAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAddRequest.Unmarshal(m, b)
}
func (m *AccountAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAddRequest.Marshal(b, m, deterministic)
}
func (dst *AccountAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAddRequest.Merge(dst, src)
}
func (m *AccountAddRequest) XXX_Size() int {
	return xxx_messageInfo_AccountAddRequest.Size(m)
}
func (m *AccountAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAddRequest proto.InternalMessageInfo

func (m *AccountAddRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountAddRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountGetRequest)(nil), "account.AccountGetRequest")
	proto.RegisterType((*AccountResponse)(nil), "account.AccountResponse")
	proto.RegisterType((*AccountAddRequest)(nil), "account.AccountAddRequest")
}

func init() {
	proto.RegisterFile("services/account/proto/account.proto", fileDescriptor_account_58c98afeafbb3e14)
}

var fileDescriptor_account_58c98afeafbb3e14 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0x87, 0xf1, 0xf4, 0xc0, 0x3c, 0x21, 0x76, 0x28, 0x57, 0x49, 0x9f, 0x4b, 0xd0, 0x11,
	0xc2, 0x74, 0x4f, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x28,
	0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x95, 0xb4, 0xb9, 0xf8, 0xa1, 0x1a, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24,
	0xb8, 0x60, 0xc6, 0x41, 0x55, 0xc3, 0x4d, 0xf7, 0x86, 0x9b, 0xee, 0x98, 0x92, 0x42, 0x84, 0xe9,
	0x20, 0xb9, 0x82, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x09, 0x26, 0x88, 0x1c, 0x8c, 0x6f,
	0xd4, 0xce, 0xc8, 0xc5, 0x0e, 0x35, 0x4d, 0xc8, 0x96, 0x8b, 0xd9, 0x3d, 0xb5, 0x44, 0x48, 0x4a,
	0x0f, 0xe6, 0x2d, 0x0c, 0x4f, 0x48, 0x49, 0xa0, 0xcb, 0xc1, 0xdc, 0xab, 0xc4, 0x00, 0xd2, 0xee,
	0x98, 0x92, 0x82, 0xa9, 0x1d, 0xe1, 0x4a, 0x7c, 0xda, 0x93, 0xd8, 0xc0, 0x81, 0x68, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x69, 0x50, 0xc5, 0xdb, 0x6c, 0x01, 0x00, 0x00,
}
