// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: account/proto/account.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account/proto/account.proto

It has these top-level messages:
	AccountGetRequest
	AccountResponse
	AccountAddRequest
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountService interface {
	Get(ctx context.Context, in *AccountGetRequest, opts ...client.CallOption) (*AccountResponse, error)
	Add(ctx context.Context, in *AccountAddRequest, opts ...client.CallOption) (*AccountResponse, error)
}

type accountService struct {
	c    client.Client
	name string
}

func NewAccountService(name string, c client.Client) AccountService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "account"
	}
	return &accountService{
		c:    c,
		name: name,
	}
}

func (c *accountService) Get(ctx context.Context, in *AccountGetRequest, opts ...client.CallOption) (*AccountResponse, error) {
	req := c.c.NewRequest(c.name, "Account.Get", in)
	out := new(AccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountService) Add(ctx context.Context, in *AccountAddRequest, opts ...client.CallOption) (*AccountResponse, error) {
	req := c.c.NewRequest(c.name, "Account.Add", in)
	out := new(AccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	Get(context.Context, *AccountGetRequest, *AccountResponse) error
	Add(context.Context, *AccountAddRequest, *AccountResponse) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler, opts ...server.HandlerOption) {
	type account interface {
		Get(ctx context.Context, in *AccountGetRequest, out *AccountResponse) error
		Add(ctx context.Context, in *AccountAddRequest, out *AccountResponse) error
	}
	type Account struct {
		account
	}
	h := &accountHandler{hdlr}
	s.Handle(s.NewHandler(&Account{h}, opts...))
}

type accountHandler struct {
	AccountHandler
}

func (h *accountHandler) Get(ctx context.Context, in *AccountGetRequest, out *AccountResponse) error {
	return h.AccountHandler.Get(ctx, in, out)
}

func (h *accountHandler) Add(ctx context.Context, in *AccountAddRequest, out *AccountResponse) error {
	return h.AccountHandler.Add(ctx, in, out)
}
